name: CI

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-rust-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-rust-${{ hashFiles('**/*.rs') }}
      - name: Format
        run: cargo fmt --all -- --check
      - name: Build
        run: cargo build
      - name: Test
        run: cargo test
      - name: Clippy
        run: cargo clippy -- -D warnings
