name: CI

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Format
        run: cargo fmt --all -- --check
      - name: Build
        run: cargo build
      - name: Test
        run: cargo test
      - name: Clippy
        run: cargo clippy -- -D warnings
